"""schema daara (maitres, classes, talibes, progressions, users)

Revision ID: 56761e53ecba
Revises: 
Create Date: 2026-06-24 10:22:38.023905

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '56761e53ecba'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('maitres',
    sa.Column('matricule', sa.String(length=20), nullable=False),
    sa.Column('nom_complet', sa.String(length=150), nullable=False),
    sa.Column('telephone', sa.String(length=30), nullable=True),
    sa.PrimaryKeyConstraint('matricule')
    )
    op.create_table('users',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('username', sa.String(length=50), nullable=False),
    sa.Column('email', sa.String(length=100), nullable=False),
    sa.Column('password', sa.String(length=255), nullable=False),
    sa.Column('created_at', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('username')
    )
    op.create_table('classes',
    sa.Column('code', sa.String(length=20), nullable=False),
    sa.Column('libelle', sa.String(length=150), nullable=False),
    sa.Column('niveau', sa.Enum('DEBUTANT', 'INTERMEDIAIRE', 'AVANCE', name='niveau'), nullable=False),
    sa.Column('maitre_matricule', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['maitre_matricule'], ['maitres.matricule'], ),
    sa.PrimaryKeyConstraint('code')
    )
    op.create_table('talibes',
    sa.Column('matricule', sa.String(length=20), nullable=False),
    sa.Column('prenom', sa.String(length=80), nullable=False),
    sa.Column('nom', sa.String(length=80), nullable=False),
    sa.Column('date_naissance', sa.Date(), nullable=True),
    sa.Column('nom_tuteur', sa.String(length=150), nullable=True),
    sa.Column('telephone_tuteur', sa.String(length=30), nullable=True),
    sa.Column('classe_code', sa.String(length=20), nullable=False),
    sa.ForeignKeyConstraint(['classe_code'], ['classes.code'], ),
    sa.PrimaryKeyConstraint('matricule')
    )
    op.create_table('progressions',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('talibe_matricule', sa.String(length=20), nullable=False),
    sa.Column('sourate', sa.String(length=100), nullable=False),
    sa.Column('nombre_versets', sa.Integer(), nullable=False),
    sa.Column('date_evaluation', sa.Date(), nullable=True),
    sa.Column('appreciation', sa.String(length=255), nullable=True),
    sa.CheckConstraint('nombre_versets >= 0', name='check_versets_positifs'),
    sa.ForeignKeyConstraint(['talibe_matricule'], ['talibes.matricule'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('progressions')
    op.drop_table('talibes')
    op.drop_table('classes')
    op.drop_table('users')
    op.drop_table('maitres')
    # ### end Alembic commands ###
